/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.javaswing;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author macbookprom1
 */
public class AddProductFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddProductFrame
     */
    
    String[] itemCategory = {
        "Quần",
        "Áo",
        "Giày",
        "Dép",
        "Túi xách"
    };
    
    public AddProductFrame() {
        initComponents();
        
        this.cbCategory.setModel(new DefaultComboBoxModel(this.itemCategory));
        
//        this và super 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfUnitPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        radioActive = new javax.swing.JRadioButton();
        radioInactive = new javax.swing.JRadioButton();
        btnAddProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên sản phẩm");

        jLabel2.setText("Mô tả sản phẩm");

        jLabel3.setText("Giá nhập sản phẩm");

        jLabel4.setText("Số lượng sản phẩm");

        jLabel5.setText("Giá bán sản phẩm");

        jLabel6.setText("Danh mục sản phẩm");

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Trạng thái");

        buttonGroup1.add(radioActive);
        radioActive.setSelected(true);
        radioActive.setText("Đang kinh doanh");

        buttonGroup1.add(radioInactive);
        radioInactive.setText("Ngừng kinh doanh");

        btnAddProduct.setText("Thêm sản phẩm");
        btnAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProductMouseClicked(evt);
            }
        });

        tableProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên sản phẩm", "Mô tả", "Giá nhập", "Số lượng", "Giá bán", "Danh mục", "Trạng thái sản phẩm"
            }
        ));
        jScrollPane1.setViewportView(tableProductList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfName)
                    .addComponent(tfDesc)
                    .addComponent(tfPrice)
                    .addComponent(tfQuantity)
                    .addComponent(tfUnitPrice)
                    .addComponent(cbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(radioActive)
                            .addComponent(radioInactive))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioActive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioInactive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseClicked
        
//      Lấy dữ liệu từ các ô TextFiled sau khi người dùng nhập vào
        String name = this.tfName.getText();
        String desc = this.tfDesc.getText();
        String price = this.tfPrice.getText();
        String quantity = this.tfQuantity.getText();
        String unitPrice = this.tfUnitPrice.getText();
        
//      Lấy tên danh mục từ ComboBox

//      Lấy vị trí item mà user đã chọn từ ComboBox
        int indexCB = this.cbCategory.getSelectedIndex();
        String categoryName = this.itemCategory[indexCB];
        
        String status = "Đang kinh doanh";
        
        if(this.radioInactive.isSelected()){
            status = "Ngừng kinh doanh";
        }
        
//      Thực hiện validate form 
//      - Tên sản phẩm bắt buộc nhập và không được bỏ trống
//      - Mô tả sản phẩm bắt buộc nhập và phải nhập ít nhất 5 TỪ 
//      - Giá của sản phẩm phải là số và lớn hơn 10000
//      - Số lượng của sản phẩm phải là số và lớn hơn 0
//      - Giá bán của sản phẩm phải là số và lớn hơn 10000 và lớn hơn giá của sp

//      "            "   => Được coi là rỗng => Có lỗi không được bỏ trống 

//      Khi có lỗi ở mỗi ô input thì các em thực hiện in ra màn hình
//      System.out.println()

//      - Tên sản phẩm => có 1 hàm kiểm tra rỗng => trả về true là rỗng => Lỗi
//      - Mô tả
//          - Sử dụng 1 hàm để loại bỏ các khoảng trắng dư thừa
//          - Dùng 1 hàm để chuyển chuỗi thành mảng thông qua các khoảng trắng
//              - Sản phẩm tốt => ["Sản", "phẩm", "tốt"]
//          - Đếm số lượng của mảng nếu nhỏ hơn 5 => Lỗi
//      - Giá => Chuyển kiểu dữ liệu chuỗi về thành số
//          - Trong quá trình chuyển có thể xảy ra lỗi Exception do user nhập chữ 
//          - Chuyển xong thì thực hiện so sánh và thông báo lỗi

//      "" || "             "
//      name.isEmpty() => "" => true, "         " => false
        if(name.isBlank()){ // "" => true,  "       " => true
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được bỏ trống");
            return;
            
//            for(int index = 0; index < 20; index++){
////                if(index == 2){
////                    break;
////                }
//
////                Chỉ lập ở TH index chia hết cho 2
//                
//                if(index % 2 != 0){
//                    
//                }
//            }
        }
        
//      trim() => Loại bỏ khoảng trắng dư trong chuỗi
//      "  abc     abbc abcbcb    " => "abc abbc abcbcb"
//      split(" ") === "abc abbc abcbcb" => ["abc", "abbc", "abcbcb"]
//      Lấy độ dài của hàng < 5 lỗi

//      join() => Chuyển mảng thành chuỗi 

//      Kiểm tra số lượng từ
        if(desc.trim().split(" ").length < 5){
            JOptionPane.showMessageDialog(this, "Mô tả sản phẩm phải có ít nhất 5 từ");
            return;
        }
        
//      Nếu TH mô tả có ít nhất 20 ký tự
//        if(desc.length() < 20){
//            
//        }

//      Giá bán => dữ liệu lấy từ TextFiled ra => String 
//      Chuyển chuỗi về thành số
        
//        Integer.parseInt(price) => Kiểu int => số nguyên

//        Float.parseFloat(price) => float => Số thực
//        Double.parseDouble(price) => double => Số thực
//        Long.parseLong(price) => long => Số thực
//      Ba kiểu dữ liệu trên khác nhau ở miền giá trị float => -3000000 <= a <= 3000000


//      Trong quá trình chuyển dữ liệu nếu mà price => chữ => xảy ra lỗi
//      try catch để bắt lỗi => Dữ liệu nhập không phải số
        int priceInt = 0;
        try{
            priceInt = Integer.parseInt(price);
    //      Kiểm tra giá không được nhỏ hơn 10.000
            if(priceInt < 10000){
//                System.out.println("Giá không được nhỏ hơn 10.000");
                JOptionPane.showMessageDialog(this, "Giá không được nhỏ hơn 10.000");
                return;
            }
        }catch(Exception e){
//            System.out.println("Giá phải là số");
            JOptionPane.showMessageDialog(this, "Giá phải là số");
            return;
        }
        
        try {
            int quantityInt = Integer.parseInt(quantity);
            if(quantityInt <= 0){
//                System.out.println("Số lượng phải lớn hơn 0");
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                return;
            }
        }catch(Exception e){
//            System.out.println("Số lượng phải là số");
            JOptionPane.showMessageDialog(this, "Số lượng phải là số");
            return;
        }
        
        try{
            int unitPriceInt = Integer.parseInt(unitPrice);
            if(unitPriceInt < 10000){
//                System.out.println("Giá bán không được nhỏ hơn 10.000");
                JOptionPane.showMessageDialog(this, "Giá bán không được nhỏ hơn 10.000");
                return;
            }else if(unitPriceInt < priceInt){
//                System.out.println("Giá bán phải lớn hơn giá nhập");
                JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn giá nhập");
                return;
            }
        }catch(Exception e){
            e.printStackTrace();
//            System.out.println("Giá bán phải là số");
            JOptionPane.showMessageDialog(this, "Giá bán phải là số");
            return;
        }
        
//      Thêm hoặc sửa dữ liệu trong DB 

    }//GEN-LAST:event_btnAddProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioActive;
    private javax.swing.JRadioButton radioInactive;
    private javax.swing.JTable tableProductList;
    private javax.swing.JTextField tfDesc;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfUnitPrice;
    // End of variables declaration//GEN-END:variables
}
