/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.javaswing;

import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author macbookprom1
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
//    Biến toàn cục 
    private int count = 0;
    String[] comboBoxItem = {"Điện thoại", "Chuột", "Bàn Phím", "Laptop", "Máy Tính Bảng"};
    
//  Đối với những control cần hiển thị giá trị mặc định
//  khi JFrame khởi tạo lên
//  Thì những giá trị và control đó bắt buộc phải được viết
//  và xử lý bên trong hàm xây dựng không tham số của JFrame
//  và viết bên dưới initComponents
    
//  Hàm xây dựng không tham số 
    public MainFrame() {
        initComponents();
        
//      Danh sách trong comboBox là 1 mảng kiểu String
//      Khai báo 1 mảng kiểu String trong mảng này có các giá trị
//      Điện thoại, Chuột, Bàn Phím, Laptop, Máy Tính Bảng
        
        this.cbCategory.setModel(new DefaultComboBoxModel(comboBoxItem));
        this.cbCategory.setSelectedIndex(3);
        
//      Lấy giá trị của item được chọn trong comboBox
        this.cbCategory.getSelectedItem(); // => Chuỗi nội dung mà user chọn 
        
        this.cbCategory.getSelectedIndex(); // Trả về vị trí mà user chọn => 0, 1, 2
        
        
        ButtonGroup btnStatus = new ButtonGroup();
        btnStatus.add(this.radioStatusActive);
        btnStatus.add(this.radioStatusInactive);
        
        ButtonGroup btnDiscount = new ButtonGroup();
        btnDiscount.add(this.radioDiscount);
        btnDiscount.add(this.radioUndiscount);
        
//        Nếu  == true => radio này được chọn và ngược lại 
        this.radioStatusActive.isSelected();
    }
    

    
//    Xử lý khi click vào Button
//    dùng hàm này để lấy ra index mà user chọn từ cb this.cbCategory.getSelectedIndex();
//    in ra nội dung mà user đã chọn
    
//    VD: User chọn điện thoại => Index = 0 => System.print => "Điện thoại"
    
//    Gợi ý mang biến comboBoxItem ra làm biến toàn cục => lấy item từ vị trí
//    index của comboBoxItem
    
    
//    id = 1 => Điện thoại, ... id = 5 => Máy tính bảng
//    index = 0,................. index = 4
    
//  Hàm xây dựng có tham số 
//    public MainFrame(String name) {
//        initComponents();
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lbTitle = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        tfPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCheckPrice = new javax.swing.JButton();
        lbErrPrice = new javax.swing.JLabel();
        tfProductName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        btnAddProduct = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        radioStatusActive = new javax.swing.JRadioButton();
        radioStatusInactive = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        radioDiscount = new javax.swing.JRadioButton();
        radioUndiscount = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java 2 Swing");

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 51, 51));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Count: 0");

        btnUpdate.setText("Count");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        jLabel1.setText("Giá tiền sản phẩm");

        btnCheckPrice.setText("Kiểm tra giá");
        btnCheckPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckPriceMouseClicked(evt);
            }
        });
        btnCheckPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPriceActionPerformed(evt);
            }
        });

        lbErrPrice.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setText("Tên sản phẩm");

        jLabel3.setText("Danh mục sản phẩm");

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Điện thoại", "Chuột", "Bàn phím" }));

        btnAddProduct.setText("Thêm sản phẩm");
        btnAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProductMouseClicked(evt);
            }
        });

        jLabel4.setText("Trạng thái");

        radioStatusActive.setSelected(true);
        radioStatusActive.setText("Còn hàng");

        radioStatusInactive.setText("Hết hàng");

        jLabel5.setText("Giảm giá");

        radioDiscount.setText("Giảm");

        radioUndiscount.setText("Không giảm giá");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrice)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbErrPrice)
                                    .addComponent(btnCheckPrice)
                                    .addComponent(jLabel1)
                                    .addComponent(btnUpdate)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfProductName)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAddProduct)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioStatusActive)
                                            .addComponent(radioDiscount))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioUndiscount)
                                            .addComponent(radioStatusInactive))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioStatusActive)
                    .addComponent(radioStatusInactive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDiscount)
                    .addComponent(radioUndiscount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddProduct)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
//        Thay đổi giá trị của lbTitle
//        lbTitle.setText("JavaSwing");
        
//        Lấy nội dung bên trong label
//        lbTitle.getText();
        
        
//        Xử lý action click 
//        Khi click vào button
//        Nếu nội dung bên trong lbTitle == "JavaSwing"
//        Thì cập nhật nội dung của lbTitle => "Java 2"
//        Ngược lại nếu nội dung bên trong lbTitle == "Java 2"
//        Thì cập nhật nội dung của lbTitle => "JavaSwing"

//        String content = lbTitle.getText();
//        
//        if(content.equals("JavaSwing")){
//            lbTitle.setText("Java 2");
//        }else {
//            lbTitle.setText("JavaSwing");
//        }


//        Khai báo 1 biến count toàn cục có giá trị là 0
//        Sau khi click vào button thì tăng count lên 1 đv
//        Sau đó cập nhật lại giá trị của title bằng nối chuỗi 

        count++;
//        lbTitle.setText("Count: " + count);

        lbTitle.setText(String.format("Count: %d", count));
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnCheckPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckPriceActionPerformed

    private void btnCheckPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckPriceMouseClicked
//      Tất cả giá trị lấy từ text field ra đều là kiểu dữ liệu Chuỗi 
        String price = tfPrice.getText();
        
//      Kiểm tra nếu người dùng nhập vào không phải số
//      => Hiển thị lỗi ở Error Label "Giá sản phẩm phải là số"
//      Kiểm tra nếu người dùng nhập vào số nhỏ hơn 0
//      => Hiển thị lỗi ở Error Label "Giá sản phẩm phải lớn hơn 0"
//      Nếu người dùng nhập thoả 2 điều kiện trên
//      => Set giá trị cho Error Label là rỗng

//      Convert String to int 

//      Chuyển thành công với điều kiện là user nhập vào đúng định dạng số 
//      Nếu user nhập vào "abc" => Lỗi => crash (treo ứng dụng)
        try{
            int priceConvert = Integer.parseInt(price);
            
            if(priceConvert <= 0){
                lbErrPrice.setText("Giá sản phẩm phải lớn hơn 0");
            }else{
                lbErrPrice.setText("");
            }
        }catch(Exception e){
            lbErrPrice.setText("Giá sản phẩm phải là số");
        }
    }//GEN-LAST:event_btnCheckPriceMouseClicked

    private void btnAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseClicked
        
//        
//        System.out.print(this.comboBoxItem[index]);


//    Click vào button thêm sản phẩm
//    Log ra thông tin
//    - Tên sản phẩm: 
//    - Danh mục sản phẩm: 
//    - Trạng thái: Còn hàng || Hết hàng
//    - Giảm giá: Giảm || Không giảm 

        System.out.println("- Tên sản phẩm: "+ this.tfProductName.getText());
        int index = this.cbCategory.getSelectedIndex();
        System.out.println("- Danh mục sản phẩm: "+ this.comboBoxItem[index]);
        
        if(this.radioStatusActive.isSelected()){
            System.out.println("- Trạng thái: Còn hàng");
        }
        
        if(this.radioStatusInactive.isSelected()){
            System.out.println("- Trạng thái: Hết hàng");
        }
        
        if(this.radioDiscount.isSelected()){
            System.out.println("- Giảm giá: Giảm");
        }
        
        if(this.radioUndiscount.isSelected()){
            System.out.println("- Giảm giá: Không giảm");
        }
    }//GEN-LAST:event_btnAddProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCheckPrice;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbErrPrice;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JRadioButton radioDiscount;
    private javax.swing.JRadioButton radioStatusActive;
    private javax.swing.JRadioButton radioStatusInactive;
    private javax.swing.JRadioButton radioUndiscount;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfProductName;
    // End of variables declaration//GEN-END:variables
}
